#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

# sudo not required for some system commands
for command in mount umount sv pacman updatedb su shutdown poweroff reboot ; do
	alias $command="sudo $command"
done; unset command

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	bc="bc -ql" \
	mkd="mkdir -pv" \
	ffmpeg="ffmpeg -hide_banner"

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
	ip="ip -color=auto"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	trem="transmission-remote" \
	YT="youtube-viewer" \
	sdn="shutdown -h now" \
	e="$EDITOR" \
	v="$EDITOR" \
	p="pacman" \
	xi="sudo xbps-install" \
	xr="sudo xbps-remove -R" \
	xq="xbps-query" \
	z="zathura" \
	magit="nvim -c MagitOnly" \
	ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/zshnameddirrc" \
	weath="less -S ${XDG_DATA_HOME:-$HOME/.local/share}/weatherreport" \

# Nikitas aliases
alias \
	mkcd='_(){ mkdir -p $1; cd $1; }; _' \
	gc="git checkout" \
	gcm="git commit -m" \
	gs="git status" \
	gd="ydiff -s -w 0 --wrap" \
	gds="ydiff -s -w 0 --wrap --cached" \
	gaa="git add -u" \
	ga="git add" \
	gca="git checkout -- ." \
	gp="git push" \
	grm="git rm" \
	gb='git for-each-ref --sort=-committerdate refs/heads/ --format="%(authordate:short) %(color:red)%(objectname:short) %(color:yellow)%(refname:short)%(color:reset) (%(color:green)%(committerdate:relative)%(color:reset))"' \
	gf='git fetch' \
	gpo="git push origin HEAD" \
	gst="git stash" \
	gstp="git stash pop" \
	grs="git restore --staged" \
	grsa="git restore --staged ." \
	gl="git log" \
	gm="git merge" \
	gpl="git pull" \
	gacm="git add -u && git commit -m" \
	xo="xdg-open" \
	history="history 1" \
	xclip="xclip -selection clipboard" \
	dcs="docker compose" \
	lvpn="cat ~/Downloads/leverxvpn/auth.cfg | tail +2 | xclip" \
	svim="goneovim -u ~/.config/SpaceVim.d/SpaceVim/init.vim" \
