#!/bin/sh

# Use neovim for vim if present.
command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d"

# Verbosity and settings that you pretty much just always are going to want.
alias \
	bat="cat /sys/class/power_supply/BAT?/capacity" \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -v" \
	mkd="mkdir -pv" \
	ffmpeg="ffmpeg -hide_banner"

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	sdn="sudo shutdown -h now" \
	f="$FILE" \
	e="$EDITOR" \
	v="$EDITOR" \
	p="sudo pacman" \
	xi="sudo xbps-install" \
	xr="sudo xbps-remove -R" \
	xq="xbps-query"


# Some other stuff
alias \
	magit="nvim -c MagitOnly" \
	ref="shortcuts >/dev/null; source ~/.config/shortcutrc" \
	weath="less -S ~/.local/share/weatherreport" \

# Nikitas aliases
alias \
	mkcd='_(){ mkdir -p $1; cd $1; }; _' \
	gc="git checkout" \
	gcm="git commit -m" \
	gs="git status" \
	gd="git diff" \
	gds="git diff --staged" \
	gaa="git add -u" \
	ga="git add" \
	gca="git checkout -- ." \
	gp="git push" \
	grm="git rm" \
	gb='git for-each-ref --sort=-committerdate refs/heads/ --format="%(authordate:short) %(color:red)%(objectname:short) %(color:yellow)%(refname:short)%(color:reset) (%(color:green)%(committerdate:relative)%(color:reset))"' \
	gf='git fetch' \
	gpo="git push origin" \
	gst="git stash" \
	gstp="git stash pop" \
	grs="git restore --staged ." \
	gl="git log" \
	gm="git merge" \
	gpl="git pull" \
	gacm="git add -u && git commit -m" \
	xo="xdg-open" \
	history="history 1" \
	xclip="xclip -selection clipboard"
